/* ============================================================
   NorthStarBI - Business Analysis

   Purpose:
   Analyze sales, product, customer, employee, store, and
   returns performance using the NorthStarBI data warehouse.
   ============================================================ */

/*Product performance: What are the top 10 products by Net Sales? Show 
Product Name, Quantity Sold, Net Sales, Cost and Profit.*/

SELECT Top 10 p.ProductName, SUM(f.Quantity) AS Total_Qty, 
SUM(f.NetSales) AS Total_Sales, SUM(f.CostAmount) AS Total_Cost, 
SUM(f.ProfitAmount) AS Total_Profit
FROM
dbo.DimProduct p
INNER JOIN
dbo.FactSales f
ON p.ProductKey = f.ProductKey
GROUP BY ProductName
ORDER BY SUM(f.NetSales) DESC;

/*Customer performance: Which 10 customers generated the most Net Sales?*/

/*SELECT q.CustomerID, q.FirstName, q.LastName, q.ranks, q.Total_Sales
FROM
(
	SELECT c.CustomerID, c.FirstName, c.LastName,
	DENSE_RANK() OVER(ORDER BY SUM(NetSales)) AS ranks, SUM(NetSales) AS Total_Sales
	FROM
	dbo.FactSales f
	INNER JOIN
	dbo.DimCustomer c
	ON f.CustomerKey = c.CustomerKey
	GROUP BY c.CustomerID, c.FirstName, c.LastName
)q 
WHERE q.ranks BETWEEN 1 AND 10;*/

SELECT Top 10 CustomerID, SUM(NetSales) AS Total_Sales
FROM
dbo.FactSales f
INNER JOIN
dbo.DimCustomer c
ON f.CustomerKey = c.CustomerKey
GROUP BY CustomerID
ORDER BY SUM(NetSales) DESC;



/*Profitability: Which products generate high sales but relatively low 
profit? Calculate a Profit Margin % using Profit Margin% = 
frac{ProfitAmount}{NetSales}\times100 */

/* Which products have Total Sales greater than the average Total Sales 
across all products?*/

WITH ProductPerformace_CTE
AS
(
	SELECT p.ProductName, SUM(NetSales) AS Total_Sales, SUM(ProfitAmount)
	AS Total_Profit, ROUND(SUM(ProfitAmount)/(NULLIF(SUM(NetSales),0)) 
	* 100,2) AS Percent_Profit_Margin
	FROM
	dbo.FactSales f
	INNER JOIN
	dbo.DimProduct p
	ON f.ProductKey = p.ProductKey
	GROUP BY ProductName
)
SELECT ProductName FROM ProductPerformace_CTE
WHERE Total_Sales > (SELECT 
AVG(Total_Sales) FROM ProductPerformace_CTE)

/*Which products generate high sales but relatively low profit?*/

WITH ProductPerformance_CTE
AS
(
	SELECT p.ProductName, SUM(NetSales) AS Total_Sales, SUM(ProfitAmount)
	AS Total_Profit, ROUND(SUM(ProfitAmount)/(NULLIF(SUM(NetSales),0)) 
	* 100,2) AS Percent_Profit_Margin
	FROM
	dbo.FactSales f
	INNER JOIN
	dbo.DimProduct p
	ON f.ProductKey = p.ProductKey
	GROUP BY ProductName
)
SELECT ProductName,
CASE
WHEN Total_Sales > (SELECT AVG(Total_Sales) FROM ProductPerformance_CTE)  
THEN 'High'
ELSE 'Low'
END AS SalesStatus,
CASE
WHEN Total_Profit < (SELECT AVG(Total_Profit) FROM ProductPerformance_CTE)  
THEN 'Low'
ELSE 'High'
END AS ProfitStatus
FROM ProductPerformance_CTE 

/*Employee performance: What are Net Sales and Profit generated by each 
employee?*/

SELECT e.EmployeeID, SUM(f.NetSales) AS Total_Sales, SUM(f.profitAmount)
AS Total_profit
FROM
dbo.FactSales f
INNER JOIN 
dbo.DimEmployee e
ON f.EmployeeKey = e.EmployeeKey
GROUP BY EmployeeID
ORDER BY SUM(f.NetSales) DESC;


/*Store performance: Compare Net Sales and Profit across stores*/

SELECT s.StoreName, SUM(f.NetSales) AS Total_Sales, SUM(f.ProfitAmount) AS
Total_Profit
FROM
dbo.DimStore s
INNER JOIN
dbo.FactSales f
ON s.StoreKey = f.StoreKey
GROUP BY s.StoreName
ORDER BY SUM(f.NetSales) DESC;


/*Returns: Which products have the highest number or value of returns? 
This will require investigating FactReturns and understanding how it 
relates to the other tables.*/

SELECT p.ProductName, SUM(r.ReturnQty) AS Total_returns, 
SUM(r.ReturnAmount) AS TotalReturnAmount
FROM
dbo.DimProduct p
INNER JOIN
dbo.FactReturns r
ON p.ProductKey = r.ProductKey
GROUP BY p.ProductName
ORDER BY SUM(r.ReturnQty) DESC;

/*Sales vs returns: Which products sell strongly but also have unusually 
high returns?*/

WITH Sales_CTE AS
(
    SELECT
        ProductKey,
        SUM(NetSales) AS Total_Sales
    FROM dbo.FactSales
    GROUP BY ProductKey
),

Returns_CTE AS
(
    SELECT
        ProductKey,
        SUM(ReturnQty) AS Return_Vol
    FROM dbo.FactReturns
    GROUP BY ProductKey
),

ProductPerform_CTE AS
(
    SELECT
        p.ProductName,
        s.Total_Sales,
        ISNULL(r.Return_Vol, 0) AS Return_Vol
    FROM dbo.DimProduct p
    INNER JOIN Sales_CTE s
        ON p.ProductKey = s.ProductKey
    LEFT JOIN Returns_CTE r
        ON p.ProductKey = r.ProductKey
)

SELECT *
FROM ProductPerform_CTE
WHERE Total_Sales >
      (SELECT AVG(Total_Sales) FROM ProductPerform_CTE)
AND Return_Vol >
      (SELECT AVG(Return_Vol) FROM ProductPerform_CTE)
ORDER BY Total_Sales DESC;
